# Generated by Django 4.1.6 on 2023-02-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilerwaste',
            name='Bt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='Bt'),
        ),
    ]
