# Generated by Django 4.1.3 on 2022-12-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilerCarbonBlackWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B', models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='В, т/год')),
                ('nc', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='n c')),
                ('qab', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='q ab')),
                ('Qi', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Qi')),
                ('year', models.IntegerField(default='2022', verbose_name='Год')),
                ('Mc', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='M c, т/год')),
            ],
        ),
        migrations.CreateModel(
            name='BoilerSulfDioxWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B', models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='В. т/год')),
                ('S', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='S r., %')),
                ('ns1', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='n s1')),
                ('ns2', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='n s2')),
                ('year', models.IntegerField(default='2022', verbose_name='Год')),
                ('Mso2', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Mso2, т/год')),
            ],
        ),
        migrations.AddField(
            model_name='boilerwaste',
            name='short_name',
            field=models.CharField(max_length=5, null=True, verbose_name='Короткое название (для автозаполнения) [5 символов]'),
        ),
    ]
