# Generated by Django 4.1.3 on 2022-12-08 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_boilercarbonblackwaste_boilersulfdioxwaste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilerSulfCarbWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(default=1, verbose_name='Квартал')),
                ('month', models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=10, verbose_name='Месяц')),
                ('year', models.IntegerField(default='2022', verbose_name='Год')),
                ('B', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='В, тыс. м3')),
                ('Mso2', models.DecimalField(decimal_places=8, default=0, max_digits=9, verbose_name='Mso2, т/год')),
                ('Mc', models.DecimalField(decimal_places=8, default=0, max_digits=9, verbose_name='M c, т/год')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.boilerwaste', verbose_name='Объект')),
            ],
        ),
        migrations.DeleteModel(
            name='BoilerCarbonBlackWaste',
        ),
        migrations.DeleteModel(
            name='BoilerSulfDioxWaste',
        ),
    ]
