# Generated by Django 4.1.3 on 2022-12-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_boilersulfcarbwaste_delete_boilercarbonblackwaste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizewaste',
            name='code_ZV',
            field=models.CharField(default='2937', max_length=5, verbose_name='Код ЗВ'),
        ),
        migrations.AddField(
            model_name='organizewaste',
            name='operating_mode',
            field=models.CharField(choices=[('Периодически', 'Периодически'), ('Постоянно', 'Постоянно')], default='Периодически', max_length=12, verbose_name='Режим работы технологического оборудования'),
        ),
        migrations.AlterField(
            model_name='boilersulfcarbwaste',
            name='B',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8, verbose_name='В, тыс. м3'),
        ),
        migrations.AlterField(
            model_name='boilersulfcarbwaste',
            name='Mc',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='M c, т/год'),
        ),
        migrations.AlterField(
            model_name='boilersulfcarbwaste',
            name='Mso2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Mso2, т/год'),
        ),
    ]
