# Generated by Django 4.1.3 on 2023-01-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0005_boilerwaste_fuel_boilerwaste_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizewaste',
            name='operating_mode',
            field=models.CharField(choices=[('Периодически', 'Периодически'), ('Постоянно', 'Постоянно')], default='Периодически', max_length=12, verbose_name='Режим работы технологического оборудования'),
        ),
        migrations.AlterField(
            model_name='unorganizewaste',
            name='harmful_substance_name',
            field=models.CharField(choices=[('Пыль зерновая м/з', 'Пыль зерновая м/з'), ('Пыль мучная', 'Пыль мучная'), ('Пыль зерновая к/з', 'Пыль зерновая к/з'), ('Пыль зерновая р/б', 'Пыль зерновая р/б'), ('фосфин (водород фосфористый)', 'фосфин (водород фосфористый)')], max_length=100, verbose_name='Вредное вещество'),
        ),
    ]
