# Generated by Django 4.1.3 on 2023-01-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0006_alter_organizewaste_operating_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unorganizewaste',
            name='code_ZV',
            field=models.CharField(default='', max_length=5, verbose_name='Код ЗВ'),
        ),
        migrations.AlterField(
            model_name='organizewaste',
            name='operating_mode',
            field=models.CharField(choices=[('Постоянно', 'Постоянно'), ('Периодически', 'Периодически')], default='Периодически', max_length=12, verbose_name='Режим работы технологического оборудования'),
        ),
        migrations.AlterField(
            model_name='unorganizewaste',
            name='obj_type',
            field=models.CharField(choices=[('Мельзавод', 'Мельзавод'), ('Крупозавод', 'Крупозавод'), ('РБ', 'РБ'), ('Фосфин', 'Фосфин')], max_length=30, verbose_name='Объект'),
        ),
    ]
