# Generated by Django 4.1.3 on 2023-01-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0007_unorganizewaste_code_zv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unorganizewaste',
            name='code_ZV',
            field=models.CharField(default='2937', max_length=5, verbose_name='Код ЗВ'),
        ),
    ]
