# Generated by Django 4.1.3 on 2023-01-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0008_alter_unorganizewaste_code_zv'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(verbose_name='Квартал')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('two', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='2 класс опасности')),
                ('three_1', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='3 класс опасности')),
                ('three_2', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='3 класс опасности (неорганизованные)')),
                ('four', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='4 класс опасности')),
            ],
        ),
    ]
