# Generated by Django 4.1.3 on 2023-01-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0009_declarationwaste'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Сумма')),
                ('quarter', models.IntegerField(verbose_name='Квартал')),
                ('year', models.IntegerField(verbose_name='Год')),
            ],
        ),
        migrations.AlterField(
            model_name='declarationwaste',
            name='three_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='3 класс опасности (организованные)'),
        ),
        migrations.AlterField(
            model_name='organizewaste',
            name='operating_mode',
            field=models.CharField(choices=[('Периодически', 'Периодически'), ('Постоянно', 'Постоянно')], default='Периодически', max_length=12, verbose_name='Режим работы технологического оборудования'),
        ),
    ]
