# Generated by Django 4.1.6 on 2023-02-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0012_alter_organizewaste_operating_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilercarbonoxwaste',
            name='B',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='В, тыс. м3'),
        ),
        migrations.AlterField(
            model_name='boilercarbonoxwaste',
            name='Cco',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Ссо, г/м3'),
        ),
        migrations.AlterField(
            model_name='boilercarbonoxwaste',
            name='Mco',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='М(CO), т/мес'),
        ),
        migrations.AlterField(
            model_name='boilercarbonoxwaste',
            name='Qh_calc',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Qн, МДж/м3'),
        ),
        migrations.AlterField(
            model_name='organizewaste',
            name='operating_mode',
            field=models.CharField(choices=[('Постоянно', 'Постоянно'), ('Периодически', 'Периодически')], default='Периодически', max_length=12, verbose_name='Режим работы технологического оборудования'),
        ),
    ]
