# Generated by Django 4.1.6 on 2023-02-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0013_alter_boilercarbonoxwaste_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilernitrogenwaste',
            name='B',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='В, тыс. м3'),
        ),
        migrations.AlterField(
            model_name='boilernitrogenwaste',
            name='Bs',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12, verbose_name='Вs, м3/с'),
        ),
        migrations.AlterField(
            model_name='boilernitrogenwaste',
            name='Knox',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12, verbose_name='Кnoх, г/МДж'),
        ),
        migrations.AlterField(
            model_name='boilernitrogenwaste',
            name='Mno',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='М(NO)'),
        ),
        migrations.AlterField(
            model_name='boilernitrogenwaste',
            name='Mno2',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12, verbose_name='М(NO2)'),
        ),
        migrations.AlterField(
            model_name='boilernitrogenwaste',
            name='Mnox',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12, verbose_name='Мnox, т/год'),
        ),
        migrations.AlterField(
            model_name='boilersulfcarbwaste',
            name='B',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=9, verbose_name='В, тыс. м3'),
        ),
        migrations.AlterField(
            model_name='boilersulfcarbwaste',
            name='Mc',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='M c, т/год'),
        ),
        migrations.AlterField(
            model_name='boilersulfcarbwaste',
            name='Mso2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Mso2, т/год'),
        ),
        migrations.AlterField(
            model_name='boilerwaste',
            name='K',
            field=models.DecimalField(decimal_places=4, default=4.1868, max_digits=6, verbose_name='К'),
        ),
        migrations.AlterField(
            model_name='declarationcalc',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='organizewaste',
            name='operating_mode',
            field=models.CharField(choices=[('Периодически', 'Периодически'), ('Постоянно', 'Постоянно')], default='Периодически', max_length=12, verbose_name='Режим работы технологического оборудования'),
        ),
    ]
